Java = ["JavaNon"]
Matlab = ["MatlabNon"]
VHDL = ["VHDLnon"]
EclipseCCR = ["EclipseRule"]
Python = ["PythonNon"]
VSCodeCcrRule = ["VSCodeNonCcrRule"]
Navigation = ["NavigationNon"]
Rust = ["RustNon"]
Prolog = ["PrologNon"]
