_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]
_enabled_ordered = ["Alphabet", "Navigation", "NavigationNon", "Numbers", "Punctuation", "Keyboard", "CasterRule", "CasterMicRule", "HardwareRule", "MouseAlternativesRule", "WindowManagementRule", "DouglasGridRule", "RainbowGridRule", "SudokuGridRule", "HMCRule", "HMCConfirmRule", "HMCDirectoryRule", "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "HistoryRule", "ChainAlias", "Alias", "BringRule", "Again", "LegionGridRule", "IERule", "DragonRule", "GrammarActivatorRule", "HooksActivationRule", "CustomVocabulary", "TaskBar", "CustomStuff", "TransformersActivationRule", "Python", "PythonNon", "ChromeRule", "VSCodeCcrRule", "VSCodeNonCcrRule", "CustomVSCode", "CustomGitBashRule"]

[whitelisted]
VSCodeCcrRule = true
SpellingWindowRule = true
Alphabet = true
CPP = true
FoxitRule = true
DragonRule = true
MyRule = true
GitBashRule = true
MSVCRule = true
TotalCommanderRule = true
MSWordRule = true
MouseAlternativesRule = true
EclipseCCR = true
WebexTeamsRule = true
Bash = true
CustomVSCode = true
PythonNon = true
CSharp = true
JetbrainsRule = true
FlashDevelopRule = true
TextManipulation = true
Keyboard = true
Go = true
VSCodeNonCcrRule = true
Again = true
NavigationNon = true
Java = true
EclipseRule = true
UnityRule = true
AtomRule = true
RustNon = true
JavaNon = true
SublimeRule = true
HTML = true
VisualStudioRule = true
WindowsSpeechRecognitionRule = true
HMCDirectoryRule = true
WindowManagementRule = true
HMCRule = true
SQL = true
SudokuGridRule = true
Rust = true
Prolog = true
CSS = true
CustomVocabulary = true
ChainAlias = true
HMCLaunchRule = true
HMCConfirmRule = true
NPPRule = true
RStudioRule = true
VHDL = true
LaTeX = true
TaskBar = true
IERule = true
DouglasGridRule = true
VHDLnon = true
JiraRule = true
SSMSRule = true
LegionGridRule = true
LyxRule = true
SQLDeveloperRule = true
SikuliRule = true
VoiceDevCommands = true
SikuliManagementRule = true
OutlookRule = true
Javascript = true
TyporaRule = true
RainbowGridRule = true
Navigation = true
ExcelRule = true
GitHubDeskRule = true
Markdown = true
KDiff3Rule = true
Numbers = true
ChromeRule = true
HMCSettingsRule = true
BringRule = true
fmanRule = true
CasterRule = true
PrologNon = true
Punctuation = true
MSTeamsRule = true
Haxe = true
Matlab = true
HardwareRule = true
AcrobatRule = true
EmacsRule = true
Python = true
FileDialogueRule = true
Dart = true
CustomStuff = true
HistoryRule = true
Rlang = true
Alias = true
FirefoxRule = true
CasterMicRule = true
CustomGitBashRule = true
SyncDirsRule = true
GitterRule = true
HMCHistoryRule = true
MatlabNon = true
