[engine]
default_mic = false
default_engine_mode = false
engine_mode = "normal"
mic_mode = "on"
mic_sleep_timer_on = true
mic_sleep_timer = 300

[paths]
USER_DIR = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster"
WSR_PATH = "C:\\Windows\\Speech\\Common\\sapisvr.exe"
RAINBOW_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\mouse\\grids.py"
CONFIGDEBUGTXT_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\configdebug.txt"
SAVED_CLIPBOARD_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\clipboard.json"
REBOOT_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\bin\\reboot.bat"
AHK_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice"
DLL_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\lib\\dll"
GIT_REPO_LOCAL_REMOTE_DEFAULT_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\bin\\share\\git_repo_local_to_remote_match.toml.defaults"
SM_HISTORY_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\sm_history.toml"
LOG_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\log.txt"
SUDOKU_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\mouse\\grids.py"
ENGINE_PATH = "C:\\Program Files (x86)\\Nuance\\NaturallySpeaking15\\Program\\natspeak.exe"
TRANSFORMERS_CONFIG_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\transformers.toml"
SIKULI_IDE = "."
HOMUNCULUS_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\hmc\\h_launch.py"
RULES_CONFIG_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\rules.toml"
SM_ALIAS_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\sm_aliases.toml"
DOUGLAS_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\mouse\\grids.py"
REMOTE_DEBUGGER_PATH = "."
BASE_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice"
SIKULI_RUNNER = "."
COMPANION_CONFIG_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\companion_config.toml"
LEGION_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\mouse\\legion.py"
SIKULI_SCRIPTS_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\sikuli"
SM_CHAIN_ALIAS_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\sm_chain_aliases.toml"
SIKULI_SERVER_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\sikuli\\server\\xmlrpc_server.sikuli"
GDEF_FILE = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\caster_user_content\\transformers\\words.txt"
REBOOT_PATH_WSR = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\bin\\reboot_wsr.bat"
SETTINGS_WINDOW_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\asynch\\settingswindow.py"
TERMINAL_PATH = "."
HOOKS_CONFIG_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\hooks.toml"
MEDIA_PATH = "C:\\Users\\AshleyShultz\\Documents\\Caster\\castervoice\\bin\\media"
PYTHONW = "C:\\Python27\\pythonw.exe"
GIT_REPO_LOCAL_REMOTE_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\git_repo_local_to_remote_match.toml"
SM_BRINGME_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\settings\\sm_bringme.toml"

[python]
pip = "pip"
version = "python"
automatic_settings = true

[hooks]
default_hooks = ["PrinterHook"]

[online]
update_interval = 7
online_mode = true
last_update_date = "2021-09-30"

[miscellaneous]
max_ccr_repetitions = 16
legion_downscale_factor = "auto"
use_aenea = false
atom_palette_wait = 30
legion_vertical_columns = 30
print_rdescripts = true
dragonfly_pause_default = 0.003
ccr_on = true
dev_commands = true
keypress_wait = 50
history_playback_delay_secs = 1.0
hmc = true

[sikuli]
version = ""
enabled = false

[Tree_Node_Path]
SM_CSS_TREE_PATH = "C:\\Users\\AshleyShultz\\AppData\\Local\\caster\\data\\sm_css_tree.toml"

[formats]
[formats.Javascript]
secondary_format = [2, 1]
text_format = [3, 1]

[formats.Java]
secondary_format = [2, 1]
text_format = [3, 1]

[formats.Python]
secondary_format = [2, 1]
text_format = [5, 3]

[formats.sequel]
secondary_format = [1, 3]
text_format = [5, 3]

[formats.Dart]
secondary_format = [2, 1]
text_format = [3, 1]

[formats.HTML]
secondary_format = [5, 2]
text_format = [5, 0]

[formats."C plus plus"]
secondary_format = [2, 1]
text_format = [3, 1]

[formats.matlab]
secondary_format = [1, 3]
text_format = [3, 1]

[formats."C sharp"]
secondary_format = [2, 1]
text_format = [3, 1]

[formats._default]
secondary_format = [1, 0]
text_format = [5, 0]

[formats.Rust]
secondary_format = [2, 1]
text_format = [5, 3]

[grammar_reloading]
reload_timer_seconds = 5
reload_trigger = "timer"

[gitbash]
fetching_time = 3
loading_time = 5
